### ISSUE TITLE
Why Monetary classes are closed to extension?

### ISSUE THREAD

**Issue by piotr-wysz** [JavaMoney/javamoney-examples#38]
Hi,
Is there any reason why classes Money, FastMoney, RoundedMoney are declared as final?
I wanted to change behavior of one method in Money class but it's not possible.
Security reasons are not relevant here because one can still implement MonetaryAmount interface and for example do it wrongly and cause some issues.
IMHO the code should be open for extension (and closed for modification). It's just a question if there are any reasons to keep these classes as final?

**Comment by stokito** [comment]
As usual and first of all, what exactly do you want to achieve and what is the method that you wanted to change? It is a big possibility that there is another way to achieve what you want or maybe you found a bug or maybe this is a good thing to implement in the library itself.

I'm not an author of the API but there is several reasons why to do that:
1. As what I said before, normally you shouldn't want to change or extend these classes. Even if you do have a valid reason for this then other programmers may not know that behavior of some method was slightly changed  and this may lead to some unexpected bugs. When we are talking about money here everything should be clear and straight as possible.
2. In fact the `Money` and `FastMoney` are implemented in a manner of Value Types like `java.lang.Integer`, `java.lang.String` or JavaTime classes `Instant`, `LocalDateTime` etc. This also means that these classes should be immutable. But if you can extend a class then you can add a mutable field.
3. The final classes may have also slightly better performance because JVM can optimize virtual method table but AFAIK modern JVMs have a good optimization in the place.

**Comment by stokito** [comment]
BTW the classes Money, FastMoney, RoundedMoney  are part of https://github.com/JavaMoney/jsr354-ri so it might be better to discuss such things there.
Since this is not an issue or a bug then I'll close the ticket if you don't mind. But we can still continue the discussion.
